name = "Overt"
uuid = "bb3e272d-c81c-4f77-93d3-09d7f700efb8"
authors = ["Amir Maleki", "Chelsea Sidrane"]
version = "0.1.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Interpolations = "0.12"
NLsolve = "4.4"
Roots = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
